const MAIN_URL = 'https://api.yakravtsova.nomoredomains.icu/api';
const SERVER_URL = 'https://api.nomoreparties.co/';
const MOVIES_URL = 'https://api.nomoreparties.co/beatfilm-movies';
const MOVIES_NUM_DESKTOP = 12;
const MOVIES_STEP_BIG_DESKTOP = 4;
const MOVIES_STEP_DESKTOP = 3;
const MOVIES_NUM_TABLET = 8;
const MOVIES_STEP_TABLET = 2;
const MOVIES_NUM_MOBILE = 5;
const MOVIES_STEP_MOBILE = 2;
const SCREEN_BIG_DESKTOP = 1240;
const SCREEN_DESKTOP = 1024;
const SCREEN_TABLET = 768;
const SCREEN_MOBILE = 480;



export {
  MAIN_URL,
  SERVER_URL,
  MOVIES_URL,
  MOVIES_NUM_DESKTOP,
  MOVIES_STEP_BIG_DESKTOP,
  MOVIES_STEP_DESKTOP,
  MOVIES_NUM_TABLET,
  MOVIES_STEP_TABLET,
  MOVIES_NUM_MOBILE,
  MOVIES_STEP_MOBILE,
  SCREEN_BIG_DESKTOP,
  SCREEN_DESKTOP,
  SCREEN_TABLET,
  SCREEN_MOBILE
}